### ISSUE TITLE
Updated timeline?

### ISSUE THREAD

**Issue by sam-writer** [grammatical/pretraining-bea2019#1]
The README suggests that the code would be posted in July. Any updates? Thank you.

**Comment by snukky** [comment]
Models and scripts will be published this or the next week, but the complete training pipeline rather in September, because I'd like to re-run it again and this takes some time.

**Comment by sam-writer** [comment]
Thanks. Let me know if I can help.

**Comment by sam-writer** [comment]
I see some code was pushed, so I will close this issue now. Thank you!
